### ISSUE TITLE
Namespace and general overview

### ISSUE THREAD

**Issue by sylus** [sylus/docker-drupalconsole#1]
Hey @RobLoach,

I was wondering if you could take a look at this repo and see if you notice anything perhaps missing or wrong about the Drupal Console integration?

Additionally  I was wondering if I should keep this repo under my org name or perhaps submit a P.R. to a new repo on your org since the other two are there (composer and drush)? Or even perhaps under the hechoendrupal org.

In an ideal world we could get Acquia to let us have drupal/drush and drupal/console in the dockerhub and also a centralized org on github for docker containers such as these but for now just looking for simplest option. :)

**Comment by sylus** [comment]
I should mention this config explicitly follows and maps to the composer docker container as supports alpine + php5 + debian.

**Comment by sylus** [comment]
Also adding @pirog

**Comment by sylus** [comment]
Test in Travis are all passing.

**Comment by sylus** [comment]
Pinging one of drupal console maintainers as well @jmolivas

**Comment by pirog** [comment]
This is exciting! We were going to spin up a console container for Kalabox things but even better to get movement on an "official" one.

**Comment by theodorosploumis** [comment]
Before going further this please see this issue: https://github.com/RobLoach/drush-docker/issues/32. The same issue exists here too. We need to use this image with docker-compose too.

I my opinion the ```drupal``` executable should be on a more generic path and it could be volumed.

Also, I think there is no need for composer and mysql to be packaged with this image since these can exist on another container but yes if you want to run the command on a local folder with no drupal installation at all then it is a need. But even this it is more "docker way" to use other linked containers instead of packaging all the stuff in one image.

I will come with a pull request but I would like to know how you are thinking about all the above. Does it make sense?

Thanks a lot.

**Comment by sylus** [comment]
I agree about the drupal (drupal console) but yes this path should be standardized with both drush-docker and docker-composer.

Composer is not packaged in this image it is called from the base container and all of its variants. I disagree with not having that dependency as it simplifies the docker layers and gives standardization with all the variants. It also aligns to official docker images which do this when possible.

Drupal is not packaged in this image either. MySQL + Postgresql libraries you do have a point about and I have no problem giving instruction that can be done in a sub container for the user. However some functionality of drupal console won't work without them. So this might need more discussion.

**Comment by RobLoach** [comment]
Am on vacation, but first review looks wonderful! Well done.

Could update the `MAINTAINER` keys, I can't take credit for the work you did here :wink: .

**Comment by theodorosploumis** [comment]
Here are some "standards" that I believe make sense when creating the official drupalconsole image. 

1) The executable should be easily volumed. Saying that it has to be on a generic path that is independent for the OS. ```/usr/local/bin/drupal``` is not a proper path, ```/drupalconsole/drupalconsole``` is an example of a good one. Also, the generated ```.drupal``` folder should be under the same path.
2) The image should have a tag for every drupalconsole release. This can be done automatically of course. 
3) For every release there should be a ```phar``` and a ```composer``` version of the tag.
4) The image should be independent from php, web server, drupal, database and composer. If any of these tools has been used to build it it should be removed afterwards on the same image (as helper software).
5) The image ENTRYPOINT should be a script that would be a wrapper to the drupalconsole command.
6) The default CMD should output the available help.

**Comment by sylus** [comment]
1) If going to be doing this namespacing i'd prefer robloach/docker-composer + robloach/drush-docker were done first as I directly follow their standards. So lets focus this over there first.
2) Already doing this
3) This is now being discussed over at: https://github.com/sylus/docker-drupalconsole/issues/5 where I am asking the other maintainers how to standardize
4) File this one against the parent repositories and any changes they make I'll follow right after.
5) Only true when alot of additional logic needed, else no need
6) Will do!

**Comment by RobLoach** [comment]
@sylus Would we move `drupalconsole` and `drush` to a `drupal` namespace on Docker Hub?

**Comment by sylus** [comment]
If eventually we got access to that org on docker hub. I would be all for it! :)
